// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function accumulate(f, xs) {
  if (xs) {
    return /* :: */[
            Curry._1(f, xs[0]),
            accumulate(f, xs[1])
          ];
  } else {
    return /* [] */0;
  }
}

exports.accumulate = accumulate;
/* No side effect */
