// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';


function validate(digits) {
  var power = function (base) {
    return Math.pow(base, String(digits).length) | 0;
  };
  var armstrong_sum = function (_param) {
    while(true) {
      var param = _param;
      var x = param[1];
      var sum = param[0];
      if (x <= 0) {
        return sum;
      } else {
        _param = /* tuple */[
          sum + power(x % 10) | 0,
          x / 10 | 0
        ];
        continue ;
      }
    };
  };
  return armstrong_sum(/* tuple */[
              0,
              digits
            ]) === digits;
}

exports.validate = validate;
/* No side effect */
