// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");

function find(xs, x) {
  var binary_search = function (xs, l, r, t) {
    var m = (l + r | 0) / 2 | 0;
    var match = l > r;
    if (match) {
      return undefined;
    } else {
      var m$prime = m;
      var xs_m = Caml_array.caml_array_get(xs, m$prime);
      if (Caml_obj.caml_lessthan(xs_m, t)) {
        return binary_search(xs, m$prime + 1 | 0, r, t);
      } else if (Caml_obj.caml_greaterthan(xs_m, t)) {
        return binary_search(xs, l, r - 1 | 0, t);
      } else {
        return m$prime;
      }
    }
  };
  return binary_search(xs, 0, xs.length - 1 | 0, x);
}

exports.find = find;
/* No side effect */
