// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var $$String = require("bs-platform/lib/js/string.js");

var partial_arg = (/[.,!?:;'"-\s]+/);

function partial_arg$1(param) {
  return param.split(partial_arg);
}

function partial_arg$2(param) {
  var param$1 = Curry._1(partial_arg$1, param);
  return $$Array.map((function (param) {
                return $$String.uppercase(param.charAt(0));
              }), param$1);
}

function abbreviate(param) {
  return Curry._1(partial_arg$2, param).join("");
}

exports.abbreviate = abbreviate;
/* partial_arg Not a pure module */
