// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function isDivisibleBy(year, value) {
  return Caml_int32.mod_(year, value) === 0;
}

function isLeapYear(year) {
  if (isDivisibleBy(year, 400) || !(isDivisibleBy(year, 100) || !isDivisibleBy(year, 4))) {
    return true;
  } else {
    return false;
  }
}

exports.isLeapYear = isLeapYear;
/* No side effect */
