// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var $$String = require("bs-platform/lib/js/string.js");

function isPangram(sentence) {
  return List.length(List.sort_uniq($$String.compare, $$Array.to_list($$String.lowercase(sentence).replace((/[^a-z]/g), "").split("")))) === 26;
}

exports.isPangram = isPangram;
/* No side effect */
