// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

function phoneNumber(str) {
  var nanp_regex = (/^\s*(?:\+1|1)?[\s.-]*\(?([2-9]\d{2})\)?[\s.-]*\(?([2-9]\d{2})\)?[\s.-]*\(?(\d{4})\)?\s*$/);
  return Belt_Option.map(Js_primitive.null_to_opt(str.match(nanp_regex)), (function (arr) {
                return Caml_array.caml_array_get(arr, 1) + (Caml_array.caml_array_get(arr, 2) + Caml_array.caml_array_get(arr, 3));
              }));
}

exports.phoneNumber = phoneNumber;
/* No side effect */
