// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var $$String = require("bs-platform/lib/js/string.js");

function is_isogram(sentence) {
  var normalised_sentence = $$String.lowercase(sentence).replace((/[\-\s]/g), "");
  return List.length(List.sort_uniq($$String.compare, $$Array.to_list(normalised_sentence.split("")))) === normalised_sentence.length;
}

exports.is_isogram = is_isogram;
/* No side effect */
