// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

function toList(score) {
  var allergen_test = function (param) {
    var allergen_score = param[0];
    return (score & allergen_score) === allergen_score;
  };
  return List.map((function (prim) {
                return prim[1];
              }), List.filter(allergen_test)(/* :: */[
                  /* tuple */[
                    1,
                    "eggs"
                  ],
                  /* :: */[
                    /* tuple */[
                      2,
                      "peanuts"
                    ],
                    /* :: */[
                      /* tuple */[
                        4,
                        "shellfish"
                      ],
                      /* :: */[
                        /* tuple */[
                          8,
                          "strawberries"
                        ],
                        /* :: */[
                          /* tuple */[
                            16,
                            "tomatoes"
                          ],
                          /* :: */[
                            /* tuple */[
                              32,
                              "chocolate"
                            ],
                            /* :: */[
                              /* tuple */[
                                64,
                                "pollen"
                              ],
                              /* :: */[
                                /* tuple */[
                                  128,
                                  "cats"
                                ],
                                /* [] */0
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]));
}

function isAllergicTo(name, score) {
  return List.exists((function (param) {
                return Caml_obj.caml_equal(name, param);
              }), toList(score));
}

exports.isAllergicTo = isAllergicTo;
exports.toList = toList;
/* No side effect */
