// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function toRna(dna) {
  var transcribeDnaNucleotide = function (param) {
    switch (param) {
      case 0 : 
          return /* U */3;
      case 1 : 
          return /* G */2;
      case 2 : 
          return /* C */1;
      case 3 : 
          return /* A */0;
      
    }
  };
  return List.map(transcribeDnaNucleotide, dna);
}

exports.toRna = toRna;
/* No side effect */
