// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

function raindrops(number) {
  var is_divisible_by = function (dividend, divisor) {
    return Caml_int32.mod_(dividend, divisor) === 0;
  };
  var sound_of_drops = function (sound, param) {
    var match = is_divisible_by(number, param[0]);
    return sound + (
            match ? param[1] : ""
          );
  };
  var rain = List.fold_left(sound_of_drops, "", /* :: */[
        /* tuple */[
          3,
          "Pling"
        ],
        /* :: */[
          /* tuple */[
            5,
            "Plang"
          ],
          /* :: */[
            /* tuple */[
              7,
              "Plong"
            ],
            /* [] */0
          ]
        ]
      ]);
  var match = rain === "";
  if (match) {
    return String(number);
  } else {
    return rain;
  }
}

exports.raindrops = raindrops;
/* No side effect */
