// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Caml_format = require("bs-platform/lib/js/caml_format.js");

function encode(str) {
  return str.replace((/(.)\1+/g), (function (matched_str, chr, _, _$1) {
                var len = matched_str.length;
                return "" + (String(len) + ("" + (String(chr) + "")));
              }));
}

function decode(str) {
  return str.replace((/(\d+)(\D)/g), (function (_, len, chr, _$1, _$2) {
                return chr.repeat(Caml_format.caml_int_of_string(len));
              }));
}

exports.encode = encode;
exports.decode = decode;
/* No side effect */
