// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var $$String = require("bs-platform/lib/js/string.js");
var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

function to_words(input) {
  return $$Array.to_list($$String.lowercase($$String.trim(input)).replace((/[^\w\s']|_/g), "").replace((/'([a-zA-Z]+)'/g), "$1").split((/[\s]+/g)));
}

function count_words(input) {
  var reducer = function (acc, x) {
    if (acc) {
      var match = acc[0];
      var word = match[0];
      if (Caml_obj.caml_equal(x, word)) {
        return /* :: */[
                /* tuple */[
                  word,
                  match[1] + 1 | 0
                ],
                acc[1]
              ];
      } else {
        return /* :: */[
                /* tuple */[
                  x,
                  1
                ],
                acc
              ];
      }
    } else {
      return /* :: */[
              /* tuple */[
                x,
                1
              ],
              acc
            ];
    }
  };
  return List.fold_left(reducer, /* [] */0, List.sort($$String.compare, input));
}

function wordCount(input) {
  return Js_dict.fromList(count_words(to_words(input)));
}

exports.wordCount = wordCount;
/* Js_dict Not a pure module */
